title: 'Hack2gether'
email: fellowship@mlh.io
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: '/prep-portfolio-22.AUG.PREP.2-team-1'
url: 'deadreyo.github.io/prep-portfolio-22.AUG.PREP.2-team-1'
twitter_username: mlhacks
github_username: mlh-fellowship

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

page_gen-dirs: false # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'fellows'
    template: 'fellows'
    name: 'name'
    title: 'name'
    dir: 'fellows'